//export const UPDATE_INPUT = 'SET_INPUT_BASE_TOKEN';

export const SET_MARKET_PAIR = 'SET_MARKET_PAIR';

export const SET_ORDER_BOOK = 'SET_ORDER_BOOK';

export const SET_EXECUTED_ORDERS = 'SET_EXECUTED_ORDERS';

export const SWITCH_TAB = 'SWITCH_TAB';

export const SET_ORDER = 'SET_ORDER';
export const SET_AVAILABLE_ORDERS_AT_PRICE = 'SET_AVAILABLE_ORDERS_AT_PRICE';

export const SET_MY_ORDERS = 'SET_MY_ORDERS';

export const SET_MY_TRADES = 'SET_MY_TRADES';

export const SET_TIMESPAN = 'SET_TIMESPAN';

export const SET_MY_UNCONFIRMEDORDERS = 'SET_MY_UNCONFIRMEDORDERS';
export const ADD_UNCONFIRMED_ORDER = 'ADD_UNCONFIRMED_ORDER';
export const REMOVE_UNCONFIRMED_ORDER = 'REMOVE_UNCONFIRMED_ORDER';
export const ADD_CANCELLING_ORDER = 'ADD_CANCELLING_ORDER';
export const REMOVE_CANCELLING_ORDER = 'REMOVE_CANCELLING_ORDER';

export const SET_MY_UNCONFIRMEDTRADES = 'SET_MY_UNCONFIRMEDTRADES';
export const ADD_UNCONFIRMED_TRADE = 'ADD_UNCONFIRMED_TRADE';
export const REMOVE_UNCONFIRMED_TRADE = 'REMOVE_UNCONFIRMED_TRADE';

// NFT Art Marketplace
export const SET_NFT_LISTINGS = 'SET_NFT_LISTINGS';
export const SET_NFT_SELECTED = 'SET_NFT_SELECTED';
export const SET_NFT_MY_ASSETS = 'SET_NFT_MY_ASSETS';
export const SET_NFT_LOADING = 'SET_NFT_LOADING';
export const SET_NFT_FILTER = 'SET_NFT_FILTER';