//export const UPDATE_INPUT = 'UPDATE_INPUT';
export const SET_BASE_TOKEN_FIELD = 'SET_INPUT_BASE_TOKEN';
export const SET_ORDER_TOKEN_FIELD = 'SET_INPUT_ORDER_TOKEN';

//export const SET_LAST_PRICE = 'SET_LAST_PRICE';
export const SET_HIGHEST_BID = 'SET_HIGHEST_BID';
export const SET_LOWEST_ASK = 'SET_LOWEST_ASK';
//export const SET_BASE_TOKEN_VOLUME = 'SET_BASE_TOKEN_VOLUME';
//export const SET_ORDER_TOKEN_VOLUME = 'SET_ORDER_TOKEN_VOLUME';

export const SET_MARKET_PAIR = 'SET_MARKET_PAIR';
export const SET_ORDER_TOKEN = 'SET_ORDER_TOKEN';
export const SET_BASE_TOKEN = 'SET_BASE_TOKEN';

export const SET_ORDER_BOOK = 'SET_ORDER_BOOK';
export const SET_ORDER_BOOK_BIDS = 'SET_ORDER_BOOK_BIDS';
export const SET_ORDER_BOOK_ASKS = 'SET_ORDER_BOOK_ASKS';

export const SET_EXECUTED_ORDERS = 'SET_EXECUTED_ORDERS';
export const SET_EXECUTED_BIDS = 'SET_EXECUTED_BIDS';
export const SET_EXECUTED_ASKS = 'SET_EXECUTED_ASKS';

export const SWITCH_TAB = 'SWITCH_TAB';