//export const UPDATE_INPUT = 'SET_INPUT_BASE_TOKEN';

export const SET_MARKET_PAIR = 'SET_MARKET_PAIR';

export const SET_ORDER_BOOK = 'SET_ORDER_BOOK';

export const SET_EXECUTED_ORDERS = 'SET_EXECUTED_ORDERS';

export const SWITCH_TAB = 'SWITCH_TAB';

export const SET_ORDER = 'SET_ORDER';

export const SET_MY_ORDERS = 'SET_MY_ORDERS';

export const SET_MY_TRADES = 'SET_MY_TRADES';

export const SET_TIMESPAN = 'SET_TIMESPAN';

export const SET_MY_UNCONFIRMEDORDERS = 'SET_MY_UNCONFIRMEDORDERS';
//export const REMOVE_UNCONFIRMED_ORDER = 'REMOVE_UNCONFIRMED_ORDER';